module.exports = {
  // AUTH
  INVALID_INPUT: 'INVALID_INPUT',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  REFRESH_TOKEN_REQUIRED: 'REFRESH_TOKEN_REQUIRED',

  // POSTS
  POST_NOT_FOUND: 'POST_NOT_FOUND',
  NO_PERMISSION: 'NO_PERMISSION',
  STATUS_REQUIRED: 'STATUS_REQUIRED',
  EVENT_DATE_REQUIRED: 'EVENT_DATE_REQUIRED',
  ADDRESS_REQUIRED: 'ADDRESS_REQUIRED',
  HASHTAG_REQUIRED: 'HASHTAG_REQUIRED',
  INVALID_LATITUDE: 'INVALID_LATITUDE',
  INVALID_LONGITUDE: 'INVALID_LONGITUDE',
  STATUS_EMPTY: 'STATUS_EMPTY',
  EVENT_DATE_EMPTY: 'EVENT_DATE_EMPTY',
  ADDRESS_EMPTY: 'ADDRESS_EMPTY',
  HASHTAG_EMPTY: 'HASHTAG_EMPTY',

  // PHOTOS
  NO_FILES_UPLOADED: 'NO_FILES_UPLOADED',
  PHOTO_NOT_FOUND: 'PHOTO_NOT_FOUND',
  FILE_REQUIRED: 'FILE_REQUIRED',
  NO_FILE_UPLOADED: 'NO_FILE_UPLOADED',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  TOO_MANY_FILES: 'TOO_MANY_FILES',
  UNEXPECTED_FILE: 'UNEXPECTED_FILE',
  UPLOAD_ERROR: 'UPLOAD_ERROR',
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',

  // USERS
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  MISSING_PASSWORD: 'MISSING_PASSWORD',

  // FAVORITES
  FAVORITE_ALREADY_EXISTS: 'FAVORITE_ALREADY_EXISTS',

  // COMMENTS
  COMMENT_EMPTY: 'COMMENT_EMPTY',

  // MESSAGES / CHAT
  MESSAGE_EMPTY: 'MESSAGE_EMPTY',

  // COMMON
  SERVER_ERROR: 'SERVER_ERROR',
}
